### ISSUE TITLE
do you have Fused-Lasso code

### ISSUE THREAD

**Issue by Sandy4321** [amkatrutsa/seminars-fivt#1]
Fused-Lasso
http://spams-devel.gforge.inria.fr/doc-python/html/doc_spams006.html

![image](https://user-images.githubusercontent.com/11426119/63808779-b8389b80-c8ee-11e9-9f90-1e6d6d016cc0.png)

**Comment by amkatrutsa** [comment]
No, I did not implement fused lasso.
